### ISSUE TITLE
Multiple minimizations in one runtime

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#602]
As we are starting to use GUNDAM for oscillation fits, p-values generation need to be extended for performing Feldman-Cousin confidence levels.

For instance in 2D contours, we need to perform a minimization of the systematic parameters while considering a fixed set of oscillation parameters: `\Delta m^2, \sin^2(2\theta)`.

This feature could be introduced by making the Minimizer class to run multiple minimizations in a loop. The conditions of each minimization should be set by the user in the config files (via a list), and the code needs to take care of storing the results.

**Comment by nadrino** [comment]
Here is a design proposal for performing a stage fit. The following config example would be put into the minimizerConfig:

```yaml
minimizationSteps:
  - name: "Pre-minimization with SIMPLEX"
    isEnabled: true
    algorithm: "Simplex"
    maxIterations: 20000 # end algo after this amount regardless of EDM
    maxFcnCalls: 20000
    saveFitResults: false
    skipHesse: true

  - name: "Base minimizer"
    legacyConfig: true # will read parameters set at the same level as `minimizationSteps`
    skipFit: true # those parameter will kept for the next steps

  - name: "Fine minimization with MIGRAD"
    algorithm: "Migrad" # run MIGRAD
```

This generalises the fact that the minimizer can run multiple instances of MINUIT in a given fit. For the oscillation parameters, one could thing about defining an extra instance which would perform multiple fit on a given grid:

```yaml
  - name: "Oscillation grid minimization"
    isEnabled: false
    algorithm: "Migrad" # run MIGRAD

    fixParameters:
      - name: "Delta m^{2}_{41} (eV^{2})"
        gridValues:
          binning:
            binningDefinition:
              - { nBins: 100, min: 1E-1, max: 1E2, logScale: true }
```
