### ISSUE TITLE
Get rid of the "mask" feature in the propagation engine

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#607]
The so called "masked" parameters in the propagator were originally introduced for performing staged breakdowns. The idea was to artificially not apply some parameters to the reweight in order to see what effect some parameter have on the total weight.

This features has never been used (as it is very limited), and the breakdowns used in our analyses can be done by performing dry runs with certain parameters sets disabled.

The main drawback of keeping such feature is the speed for propagating parameters. In fact, checking wheather or not a parameter is effectively masked needs to be done for each event and each parameter. 

In addition, this feature isn't supported by the GPU extension.

**Comment by nadrino** [comment]
Note: while getting rid of all those instances, I realised this "mask" feature is used for the toy generation of the OA. As we use real toys to propagate the detector systematics, the obsnorm parameter are masked during the propagation.

A better way of handling this needs to be implemented.

**Comment by nadrino** [comment]
Here is a new design for masking parameter during the generation of toys:

```yaml
          - name: "pValueToys"

            # copy pars from MC
            fromMc: true
            
            overrideParameter:
              - name: "ND280 Detector Systematics"
                isEnabled: false # toy generation is handled by the psyche selections
```

The `overrideParameter` option would override the ParameterSet/Parameter config. This requires to implement a full reload of the parameter config once the toy experiment has been generated.
