### ISSUE TITLE
Parameter binning failed to be read

### ISSUE THREAD

**Issue by XingyuZhao1995** [gundam-organization/gundam#649]
I'm using the latest branch `v1.9.0f+570-g2fbc22f4` but found the parameter binning could not be correctly input.

In `ParameterSet.cpp` function `ParameterSet::configureImpl` the binning is read like
```
        JsonType parameterBinning{};
        GenericToolbox::Json::fetchValue<JsonType>(dialSetDef, {{"binning"}, {"parametersBinningPath"}}, parameterBinning);
```
However the `parameterBinning` is still empty and no binning is read, so that it showed to me a message like that
```
2024.10.02 11:27:57 ERROR ParameterSet: (virtual void ParameterSet::configureImpl()): Could not figure out the number of parameters to be defined for the set: template parameters C
libc++abi: terminating due to uncaught exception of type std::runtime_error: exception thrown by the logger:_nbParameterDefinition_==-1: "Could not figure out the number of parameters to be defined for the set: " << _name_
```

 I defined the binning like 
```
- name: template parameters C
  isEnabled: true
  nominalStepSize: 0.3
  useOnlyOneParameterPerEvent: true
  dialSetDefinitions:
    - applyOnDataSets: ["ND280"]
      parametersBinningPath: "./inputs/parameters/template/Carbon_2D_2.txt"
      applyCondition: "[signal_tag] == 1 && [target] == 0 && [index2_true] >= 0"
      minDialResponse: -30
      maxDialResponse: 30      
      printDialsSummary: true
  printDialSetsSummary: true
```
but this worked properly for the old GUNDAM versions.
