### ISSUE TITLE
Sequencial minimizer

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#737]
In order to perform viable Feldman Cousins, we want to implement a new way of setting up the minimizer. For instance a usual fit as for T2K could be writen like this:

```yaml
# https://root.cern.ch/doc/master/NumericalMinimization_8C.html

type: "RootMinimizer"

minimizationSequence:

  # Pre-fit
  - action: "Minimize"
    minimizer: "Minuit2"
    algorithm: "Simplex"
    strategy: 1
    tolerance: 100
    maxFcnCalls: 20000
    printLevel: 1

  # Precise fit
  - action: "Minimize"
    algorithm: "Migrad"
    tolerance: 1E-2
    maxFcnCalls: 1E9

  # Post-fit error calculation
  - action: "CalcErrors"
    algorithm: "Hesse"
```

**Comment by nadrino** [comment]
In order to generalize the handling of the minimizer engine, one need to be able to control which data/MC should be set. For instance here, let's generate a "toy" that we would like to fit:

```yaml
minimizationSequence:

  - name: "Throw a toy"
    action: "editDataPropagator"
    [...]
```

**Comment by ClarkMcGrew** [comment]
We need something general enough to handle "profiling" and FC, as well as the MCMC sequencing. I think that means looping control (but probably NOT conditionals).

**Comment by ClarkMcGrew** [comment]
Also, profiling will require, "fix/set variable", "increment variable" and "decrement variable".  I'm thinking that a *VERY* limited python (or ROOT) interface might be a good idea.  Gundam would be the driver, but the sequence could be handled by a real interpreter (not hand rolled).  

p.s. I like the idea of using ROOT since we already link to it so it minimizes our dependencies, and it could export either C++ish or Python syntax.

**Comment by nadrino** [comment]
Using the python interface will always be a possibily without implementing anything. The only drawback would be from having to write all the results in the output ROOT file.

This will get generallized as we think about cases. The looping control are pretty basic so a YAML implementation is viable. I don't think anyone would need more that this.

**Comment by ClarkMcGrew** [comment]
I think this is the wrong direction since you are trying to beat a data transport format into a scripting language (and you are talking about scripting).  It has been tried, and turns into a mess.  

There are a lot of good options for this sort of thing. 
1) We can do it using rootcling to wrap what we decide to export for TROOT::ProcessLine and/or TPython::Exec.  This has the "disadvantage" that all of ROOT becomes available, but that's a matter of "trusting" our users.
2) If that's not sandboxy enough for you, lua is very small and good at sandboxing.  Users would only have access to what we want to expose.

Both of those can be easily fed using standard yaml multi-line strings.

**Comment by nadrino** [comment]
Alright so if I understood correctly, you'd like to write code directly in the YAML file that would be interpreted with TROOT::ProcessLine?

**Comment by ClarkMcGrew** [comment]
I've used this idiom a bit outside of "physics".  This is hacked straight from the keyboard, so I may botch it, but generically, it looks like

```yaml
- pythonSequence: |
     for name in ['fred', 'charly', 'beatrice']:
         print('My name is ', name)

- moreYamlStuff: "Keep on truckin"
```

Then the "python" string gets fed to `TPython::Exec(char *)` (or `TROOT::ProcessLine(char *)` if we opt for C++ syntax).

For our "command oriented case", I'd implement a simple syntax where your sequence above might look something like (the specifics would need thought):

```yaml
- sequence: |
     for toy in range(100000):
         gundam.data.makeToy()
         gundam.minimizer.overrideAlgorithm("simplex")
         gundam.minimizer.overrideStrategy(1)
         gundam.minimizer()
         gundam.minimizer.overrideAlgorithm("migrad")
         gundam.minimizer()
```
The commands can be implemented with a simple UI class structure that gets exposed to python (or root macros) using rootcling (hand wrapping is possible, as is swig, etc, but I suggest rootcling since it's already part of our tool set).   This is not how I would do it (too brute force), but simplistic "command" classes for the above might look something like
```cxx
struct MinimizerUI {
    void help();
    void overrideAlgorithm(std::string);
    void overrideStrategy(int);
    operator ()(void);
};
struct GundamUI {
   void help();
   MinimizerUI minimizer;
   DataSampleUI data;
}
GundamUI gundam;
```
The same UI classes can also be directly used in c++ (e.g. to implement the gundamFitter.cxx actions), but we might not want to do that.

**Comment by nadrino** [comment]
Thank you Clark, I think I see what you mean.

In fact the python sequence does not need to rely on any additional struct; the python interface already provide method access to the user.

For this tho, I don't want to provide "scripting power" to the user through the config files. User just need to set basic instructions in a list and let GUNDAM setup everything in the right order.

Scripting requires the user to know the internal structure of GUNDAM, which was never the intention. For more advanced / adventurous users, the python interface is made for them.

**Comment by nadrino** [comment]
Alright I think I get it, I think the main difference is that you generalise more widely the way to setup the fit.

In my case it's a simple parameter override with very limited actions: `minimize` and `calcError`. This approach won't change much to the original code, but allow the flexibility of editing fit options in steps.

In the end our two approaches are orthogonal, so we can implement both them. 

I keep on writing mine as this will solve the issue of the output folder for the fit results that both of us need.

**Comment by scalvez** [comment]
I can see at least three different use cases for sequential/repeated fits:
  - fit the same data but starting the minimizer at different seed points and keep only the best fit result, e.g., making sure the fit is not stuck in a local minimum.
  - fit the same data but fixing some parameter of interest at different values, e.g., profiling.
  - fitting different fake data back to back, e.g,. FC pseudoexperiments.
  
Then there could be a combination of two or more of those modes.

I think having a dedicated --profile option for gundamFitter where users can provide a config file where they specify which parameter(s) they want to fix and at which values (e.g. with a range and a number of steps, or a number of steps and a step size, or with a custom list of values) could be useful and would simplify the implementation of the support for the combination of the different modes of repeated fits.

**Comment by scalvez** [comment]
For the first mode above, starting different fits at different points could be parallelized since they are independent (though Minuit2 might not be perfectly thread safe)

**Comment by nadrino** [comment]
Definitely some features that would be very useful. In each of the task entries the idea was to provide the appropriate info the fitter (fixing parameters, different starting point etc...).

Instead of a dedicated `--profile` tho, I would rather stick to a pure config file feature (callable with `--override-file`).

> For the first mode above, starting different fits at different points could be parallelized since they are independent (though Minuit2 might not be perfectly thread safe)

Are you thinking these fit would happen in the same runtime? Or running different `gundamFitter` instances?

**Comment by scalvez** [comment]
The --profile option would take a single config file. With --override-file, would you have to specify a different config file for each point profiled ?

Yes, the search for local minima would mostly make sense in the same gundamFitter instance.

**Comment by nadrino** [comment]
> The --profile option would take a single config file. With --override-file, would you have to specify a different config file for each point profiled ?

It would be much easier to maintain if we add a dedicated option in the sequencer (`minimizerTaskList`). Something like:
```yaml
  - name: "Profiling"
    profilingSequence:
       parameter: "name to the parameter"
       fixedValuesList: [, ,] # or reference to a binning file
       # sub sequencer task
       minimizerTaskList:
        - name: "Minimization" 
          action: "minimize"
          algorithm: "Migrad"
          tolerance: 1E-2
          maxFcnCalls: 1E9
```

This way the sequencer would understand that it needs to perform an action for each of the fit values, for which it has to minimize.

I guess having a dedicated `--profile` option would add a dedicated config parsing; having it included within the sequencer config would make it generalized already.
