### ISSUE TITLE
Adding option to add a weight expression to the nominal value

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#756]
Most of the fake data studies need to add a custom weight to the nominal one of each event.

In the current version of GUNDAM, one can only attribute a weight through a TTreeFormula. One could setup an additional weight formula from the variable expression the user specify. For instance:

```yaml
fitterEngineConfig:
  propagatorConfig:
    dataSetList:
      - name: "ND280"

        # running without -a will automatically load the FDS
        selectedDataEntry: "fds"

        data:
          - name: "fds"

            # nominal weight product
            nominalWeightFormula:
              - "FluxWeight[0] * PileUpWeight"
              - "POTWeight" 
              - "(DetNomWeight > 10) ? 10: (DetNomWeight < 0 ? 0 : DetNomWeight)"
              - "XsecNomWeight"

            variableDict:
              - { name: "FDS_weight_SF_to_LFG",            expr: "FDSWeight[0]" }

            eventVariableAsWeight: "FDS_weight_SF_to_LFG"
```

The event weight would be evaluated using:
```
nominalEventWeight = nominalWeightFormula * eventVariableAsWeight
```

This feature helps keeping track of the actual weight applied in override files for a given fit, while keeping the `nominalWeightFormula` as defined as the MC.
